sudo: false

dist: trusty

language: java

osx_image: xcode9

matrix:
  include:
    - os: osx
    - os: linux

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - nvm install 6
  - npm install
  - npm prune

before_script:
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script:
  - npm test
  - npm run dist
  - npm run pack
  - cd api
  - mvn -B checkstyle:check
  - mvn -B compile
  - mvn -B test-compile
  - mvn -B install

notifications:
  email: false
