sudo: false
os: linux
language: java
env:
  - SRC_DIR=backend
  - SRC_DIR=admin-portal
  - SRC_DIR=frontend
  - SRC_DIR=provider-portal
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - nvm install 6
before_script:
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
script:
  - cd $SRC_DIR
  - if [ $SRC_DIR == "backend" ]; then
      mvn -B checkstyle:check;
    else
      yarn install;
      yarn lint;
    fi
notifications:
  email: false
