sudo: false
language: node_js
node_js:
  - 6
  - 8
env:
  - SRC_DIR=admin-portal
  - SRC_DIR=frontend
  - SRC_DIR=provider-portal
script:
  - cd $SRC_DIR
  - yarn install
  - yarn lint
notifications:
  email: false
